Testing catch block with URI Error PASSED!
