Testing catch block with Reference Error PASSED!
