Testing catch block with Range Error PASSED!
