Testing catch block with Argument Error PASSED!
